### ISSUE TITLE
Error: only one instance of babel/polyfill is allowed

### ISSUE THREAD

**Issue by fkrauthan** [elierotenberg/react-nexus-app#1]
I can't get this code to run. If I checkout this project run `npm install` and after that `gulp` I get the following error:

```
[21:35:15] Starting 'css'...
events.js:85
      throw er; // Unhandled 'error' event
            ^
Error: only one instance of babel/polyfill is allowed
    at Object.<anonymous> (/home/fkrauthan/Documents/IdeaProjects/github/SimpleTwitter/client2/tmp/react-nexus-app/node_modules/react-nexus/node_modules/babel/lib/babel/polyfill.js:4:9)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object.<anonymous> (/home/fkrauthan/Documents/IdeaProjects/github/SimpleTwitter/client2/tmp/react-nexus-app/node_modules/react-nexus/node_modules/babel/polyfill.js:1:80)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object.<anonymous> (/home/fkrauthan/Documents/IdeaProjects/github/SimpleTwitter/client2/tmp/react-nexus-app/node_modules/react-nexus/dist/index.js:5:1)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object.<anonymous> (/home/fkrauthan/Documents/IdeaProjects/github/SimpleTwitter/client2/tmp/react-nexus-app/dist/components/About.js:15:13)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
```

Any ideas why this happens? I am using nodejs version `v0.12.0`

**Comment by eTorAken** [comment]
Related to [this](https://github.com/babel/babel/issues/1019). Make sure all the `babel` versions are the same in your project and its own dependencies (or remove `babel` from dependencies).

**Comment by fkrauthan** [comment]
I've tried exactly this project without changing anything and got that issue.

**Comment by eTorAken** [comment]
It was a workaround to work with `react-nexus-app` waiting for a fix ;)

It is a known issue, `isomorphic-router`, `lifespan`, `nexus-flux`, `nexus-flux-socket.io`, `react-animate` and `react-nexus` are dependencies which are using different versions of `babel`. We are working on this.

**Comment by fkrauthan** [comment]
Ah ok. Shouldn't the libs itself beeing delivered without babel?

**Comment by elierotenberg** [comment]
`babel`-transpiled code requires `babel/polyfill` to be loaded, so the dist code (transpiled) still requires it to run.

Also `react-nexus-app` is pretty outdated, I'll update it with the next release of `react-nexus`, which will feature `react@0.13.x` and higher-order components instead of mixins :)

**Comment by eTorAken** [comment]
Ready for action: elierotenberg/react-nexus#14
